export { default as askForTemplate } from "./askForTemplate"
export { default as createVhost } from "./createVhost"
export { default as deleteHosts } from "./deleteHosts"
export { default as replacePlaceholders } from "./replacePlaceholders"
export { default as restartNginx } from "./restartNginx"
export { default as nginxInstalled } from "./nginxInstalled"
